### ISSUE TITLE
Installation from pip doesn't work out of the box

### ISSUE THREAD

**Issue by danielpops** [duo-labs/parliament#1]
The tool is non-functional when following the installation instructions, due to a missing iam_definition.json file from whichever folder you run the tool from:

```
dpopes@dev62-uswest1adevc (devbox):~ [09:50:33] ✓
$ virtualenv --python=python3.6 ./venv-parliament
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /nail/home/dpopes/venv-parliament/bin/python3.6
Also creating executable in /nail/home/dpopes/venv-parliament/bin/python
Installing setuptools, pip, wheel...source done.
dpopes@dev62-uswest1adevc (devbox):~ [09:50:47] ✓
$ source venv-parliament/bin/activate
(venv-parliament) dpopes@dev62-uswest1adevc (devbox):~ [09:50:51] ✓
$ pip install parliament
Collecting parliament
  Downloading https://files.pythonhosted.org/packages/b3/91/c487c5c69032e71ea3340b037f71dbbd2d958dc59e809cd97bfe307f5b08/parliament-0.2.2.tar.gz
Collecting boto3
  Using cached https://files.pythonhosted.org/packages/8e/a9/1ceaeda8aa5d3effc9098ae301820e27bf54c4000ec6f8ec79f9b265c50e/boto3-1.10.19-py2.py3-none-any.whl
Collecting jmespath
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Processing ./.cache/pip/wheels/d9/45/dd/65f0b38450c47cf7e5312883deb97d065e030c5cca0a365030/PyYAML-5.1.2-cp36-cp36m-linux_x86_64.whl
Collecting s3transfer<0.3.0,>=0.2.0
  Using cached https://files.pythonhosted.org/packages/16/8a/1fc3dba0c4923c2a76e1ff0d52b305c44606da63f718d14d3231e21c51b0/s3transfer-0.2.1-py2.py3-none-any.whl
Collecting botocore<1.14.0,>=1.13.19
  Using cached https://files.pythonhosted.org/packages/18/e5/0f29669244ffacc15c4cec9e10d75c26e7d300e1786e79514e62373e648c/botocore-1.13.19-py2.py3-none-any.whl
Collecting python-dateutil<2.8.1,>=2.1; python_version >= "2.7"
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting urllib3<1.26,>=1.20; python_version >= "3.4"
  Using cached https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl
Collecting docutils<0.16,>=0.10
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting six>=1.5
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Building wheels for collected packages: parliament
  Building wheel for parliament (setup.py) ... done
  Created wheel for parliament: filename=parliament-0.2.2-cp36-none-any.whl size=16196 sha256=a06908b3ba7624786287a887fc4a8ca2dfa8171e666a16937169a92c50147f3e
  Stored in directory: /nail/home/dpopes/.cache/pip/wheels/49/d8/e0/9b4a536b66f1b2dd0e0a49535457c9095d065521bfaba39572
Successfully built parliament
Installing collected packages: jmespath, six, python-dateutil, urllib3, docutils, botocore, s3transfer, boto3, pyyaml, parliament
Successfully installed boto3-1.10.19 botocore-1.13.19 docutils-0.15.2 jmespath-0.9.4 parliament-0.2.2 python-dateutil-2.8.0 pyyaml-5.1.2 s3transfer-0.2.1 six-1.13.0 urllib3-1.25.7
(venv-parliament) dpopes@dev62-uswest1adevc (devbox):~ [09:50:59] ✓
$ parliament --help
Traceback (most recent call last):
  File "/nail/home/dpopes/venv-parliament/bin/parliament", line 5, in <module>
    from parliament.cli import main
  File "/nail/home/dpopes/venv-parliament/lib/python3.6/site-packages/parliament/__init__.py", line 15, in <module>
    iam_definition = json.load(open(iam_definition_path, "r"))
FileNotFoundError: [Errno 2] No such file or directory: '/nail/home/dpopes/venv-parliament/lib/python3.6/site-packages/parliament/iam_definition.json'
```

**Comment by danielpops** [comment]
Also, satisfying that requirement and placing a file there results in a different error => 

```
(venv-parliament) dpopes@dev62-uswest1adevc (devbox):~ [09:54:23] ✗
$ cp scratch/parliament/parliament/iam_definition.json ./venv-parliament/lib/python3.6/site-packages/parliament/
(venv-parliament) dpopes@dev62-uswest1adevc (devbox):~ [09:54:56] ✓
$ parliament --help
Traceback (most recent call last):
  File "/nail/home/dpopes/venv-parliament/bin/parliament", line 5, in <module>
    from parliament.cli import main
ModuleNotFoundError: No module named 'parliament.cli'
```

**Comment by 0xdabbad00** [comment]
It should hopefully work now with parliament `0.2.3`. Sorry for these initial issues. I couldn't test until the project went public and it's release today kind of caught me off guard.  CloudMapper 2.8.0, committed just now, seems to work successfully with this new release.  I'll check some more things tonight.

**Comment by danielpops** [comment]
@0xdabbad00 the `parliament.cli` issue still exists => 

```
dpopes@dev62-uswest1adevc (devbox):~ [10:42:23] ✓
$ virtualenv --python=python3.6 ./venv-parliament
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /nail/home/dpopes/venv-parliament/bin/python3.6
Also creating executable in /nail/home/dpopes/venv-parliament/bin/python
Installing setuptools, pip, wheel...done.
dpopes@dev62-uswest1adevc (devbox):~ [10:42:31] ✓
$ source venv-parliament/bin/activate
(venv-parliament) dpopes@dev62-uswest1adevc (devbox):~ [10:42:39] ✓
$ pip install parliament
Collecting parliament
  Downloading https://files.pythonhosted.org/packages/cc/7c/34ef3de8818bf21cd7a40aa3ff852d9f3cb211d4f946025eca6e31b65671/parliament-0.2.3.tar.gz (215kB)
     |████████████████████████████████| 225kB 44.1MB/s
Collecting boto3
  Using cached https://files.pythonhosted.org/packages/8e/a9/1ceaeda8aa5d3effc9098ae301820e27bf54c4000ec6f8ec79f9b265c50e/boto3-1.10.19-py2.py3-none-any.whl
Collecting jmespath
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Processing ./.cache/pip/wheels/d9/45/dd/65f0b38450c47cf7e5312883deb97d065e030c5cca0a365030/PyYAML-5.1.2-cp36-cp36m-linux_x86_64.whl
Collecting botocore<1.14.0,>=1.13.19
  Using cached https://files.pythonhosted.org/packages/18/e5/0f29669244ffacc15c4cec9e10d75c26e7d300e1786e79514e62373e648c/botocore-1.13.19-py2.py3-none-any.whl
Collecting s3transfer<0.3.0,>=0.2.0
  Using cached https://files.pythonhosted.org/packages/16/8a/1fc3dba0c4923c2a76e1ff0d52b305c44606da63f718d14d3231e21c51b0/s3transfer-0.2.1-py2.py3-none-any.whl
Collecting docutils<0.16,>=0.10
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting urllib3<1.26,>=1.20; python_version >= "3.4"
  Using cached https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl
Collecting python-dateutil<2.8.1,>=2.1; python_version >= "2.7"
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting six>=1.5
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Building wheels for collected packages: parliament
  Building wheel for parliament (setup.py) ... done
  Created wheel for parliament: filename=parliament-0.2.3-cp36-none-any.whl size=222843 sha256=61f6c44b985d6693ade17a32d41edce71d8250982dd51b2ea74579b74745c1f6
  Stored in directory: /nail/home/dpopes/.cache/pip/wheels/bf/2a/5a/a7949ff2632a17f9fab772e5bf248fe28df0d2b5c0cd9267d3
Successfully built parliament
Installing collected packages: jmespath, docutils, urllib3, six, python-dateutil, botocore, s3transfer, boto3, pyyaml, parliament
Successfully installed boto3-1.10.19 botocore-1.13.19 docutils-0.15.2 jmespath-0.9.4 parliament-0.2.3 python-dateutil-2.8.0 pyyaml-5.1.2 s3transfer-0.2.1 six-1.13.0 urllib3-1.25.7
(venv-parliament) dpopes@dev62-uswest1adevc (devbox):~ [10:42:49] ✓
$ which parliament
/nail/home/dpopes/venv-parliament/bin/parliament
(venv-parliament) dpopes@dev62-uswest1adevc (devbox):~ [10:42:50] ✓
$ parliament --help
Traceback (most recent call last):
  File "/nail/home/dpopes/venv-parliament/bin/parliament", line 5, in <module>
    from parliament.cli import main
ModuleNotFoundError: No module named 'parliament.cli'
```

**Comment by 0xdabbad00** [comment]
I think it is resolved now in 0.2.4. I'm sorry for this trouble.

**Comment by danielpops** [comment]
Looks good now @0xdabbad00! Thanks!

**Comment by azarboon** [comment]
still i have this issue
