### ISSUE TITLE
--include-community-auditors cli options crash with Python 3.10.5

### ISSUE THREAD

**Issue by smoy** [duo-labs/parliament#217]
OS version: macOS 12.4
Python version: Python 3.10.5

```
./bin/parliament  --include-community-auditors --file <file_under_audit>
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/Users/REDACT/test/parliament/venv/lib/python3.10/site-packages/parliament/community_auditors')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/REDACT/test/parliament/parliament/./bin/parliament", line 10, in <module>
    main()
  File "/Users/REDACT/test/parliament/venv/lib/python3.10/site-packages/parliament/cli.py", line 320, in main
    policy = analyze_policy_string(
  File "/Users/REDACT/test/parliament/venv/lib/python3.10/site-packages/parliament/__init__.py", line 69, in analyze_policy_string
    policy.analyze(
  File "/Users/REDACT/test/parliament/venv/lib/python3.10/site-packages/parliament/policy.py", line 339, in analyze
    for importer, name, _ in pkgutil.iter_modules(
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pkgutil.py", line 129, in iter_modules
    for i in importers:
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1632, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1504, in __init__
  File "<frozen importlib._bootstrap_external>", line 182, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

**Comment by smoy** [comment]
This is already fixed by #207 but a new package has not been released yet.
