### ISSUE TITLE
Parliament fails to parse policy iam_self_management from terraform-aws-modules/aim

### ISSUE THREAD

**Issue by niooss-ledger** [duo-labs/parliament#236]
Hello,
While trying to run parliament on the output of `aws iam get-account-authorization-details`, I got a fatal error:

```text
Traceback (most recent call last):
  File "/usr/local/bin/parliament", line 33, in <module>
    sys.exit(load_entry_point('parliament==1.6.2', 'console_scripts', 'parliament')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/parliament-1.6.2-py3.11.egg/parliament/cli.py", line 273, in main
  File "/usr/local/lib/python3.11/site-packages/parliament-1.6.2-py3.11.egg/parliament/__init__.py", line 73, in analyze_policy_string
  File "/usr/local/lib/python3.11/site-packages/parliament-1.6.2-py3.11.egg/parliament/policy.py", line 269, in analyze
  File "/usr/local/lib/python3.11/site-packages/parliament-1.6.2-py3.11.egg/parliament/statement.py", line 294, in __init__
  File "/usr/local/lib/python3.11/site-packages/parliament-1.6.2-py3.11.egg/parliament/statement.py", line 1008, in analyze_statement
  File "/usr/local/lib/python3.11/site-packages/parliament-1.6.2-py3.11.egg/parliament/statement.py", line 526, in _check_condition
  File "/usr/local/lib/python3.11/site-packages/jsoncfg/config_classes.py", line 327, in __getattr__
    raise JSONConfigNodeTypeError(
jsoncfg.config_classes.JSONConfigNodeTypeError: Expected a ConfigJSONObject but found ConfigJSONArray. You are trying to get an item from an array as if it was an object. item=value [line=1;col=1131]
```

I extracted the problematic policy in a JSON file named `iam_self_management.json` (copied here with light editing):

```json
        {
            "PolicyName": "IAMSelfManagement-20210101000000001000000001",
            "PolicyId": "ANPXXXXXXXXXXXXXXXXXX",
            "Arn": "arn:aws:iam::123456789012:policy/IAMSelfManagement-20210101000000001000000001",
            "Path": "/",
            "DefaultVersionId": "v1",
            "AttachmentCount": 1,
            "PermissionsBoundaryUsageCount": 0,
            "IsAttachable": true,
            "CreateDate": "2021-01-01T00:00:00+00:00",
            "UpdateDate": "2021-01-01T00:00:00+00:00",
            "PolicyVersionList": [
                {
                    "Document": {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Sid": "AllowSelfManagement",
                                "Effect": "Allow",
                                "Action": [
                                    "iam:UploadSigningCertificate",
                                    "iam:UploadSSHPublicKey",
                                    "iam:UpdateUser",
                                    "iam:UpdateLoginProfile",
                                    "iam:UpdateAccessKey",
                                    "iam:ResyncMFADevice",
                                    "iam:List*",
                                    "iam:Get*",
                                    "iam:GenerateServiceLastAccessedDetails",
                                    "iam:GenerateCredentialReport",
                                    "iam:EnableMFADevice",
                                    "iam:DeleteVirtualMFADevice",
                                    "iam:DeleteLoginProfile",
                                    "iam:DeleteAccessKey",
                                    "iam:CreateVirtualMFADevice",
                                    "iam:CreateLoginProfile",
                                    "iam:CreateAccessKey",
                                    "iam:ChangePassword"
                                ],
                                "Resource": [
                                    "arn:aws:iam::123456789012:user/*/${aws:username}",
                                    "arn:aws:iam::123456789012:user/${aws:username}",
                                    "arn:aws:iam::123456789012:mfa/${aws:username}"
                                ]
                            },
                            {
                                "Sid": "AllowIAMReadOnly",
                                "Effect": "Allow",
                                "Action": [
                                    "iam:List*",
                                    "iam:Get*"
                                ],
                                "Resource": "*"
                            },
                            {
                                "Sid": "AllowDeactivateMFADevice",
                                "Effect": "Allow",
                                "Action": "iam:DeactivateMFADevice",
                                "Resource": [
                                    "arn:aws:iam::123456789012:user/*/${aws:username}",
                                    "arn:aws:iam::123456789012:user/${aws:username}",
                                    "arn:aws:iam::123456789012:mfa/${aws:username}"
                                ],
                                "Condition": {
                                    "Bool": {
                                        "aws:MultiFactorAuthPresent": [
                                            "true"
                                        ]
                                    },
                                    "NumericLessThan": {
                                        "aws:MultiFactorAuthAge": [
                                            "3600"
                                        ]
                                    }
                                }
                            }
                        ]
                    },
                    "VersionId": "v1",
                    "IsDefaultVersion": true,
                    "CreateDate": "2021-01-01T00:00:00+00:00"
                }
            ]
        }
```

When parsing this policy, the same error happens:

```text
$ jq '.PolicyVersionList[].Document' < iam_self_management.json | parliament
Traceback (most recent call last):
  File "/usr/local/bin/parliament", line 33, in <module>
    sys.exit(load_entry_point('parliament==1.6.2', 'console_scripts', 'parliament')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/parliament-1.6.2-py3.11.egg/parliament/cli.py", line 321, in main
  File "/usr/local/lib/python3.11/site-packages/parliament-1.6.2-py3.11.egg/parliament/__init__.py", line 73, in analyze_policy_string
  File "/usr/local/lib/python3.11/site-packages/parliament-1.6.2-py3.11.egg/parliament/policy.py", line 269, in analyze
  File "/usr/local/lib/python3.11/site-packages/parliament-1.6.2-py3.11.egg/parliament/statement.py", line 294, in __init__
  File "/usr/local/lib/python3.11/site-packages/parliament-1.6.2-py3.11.egg/parliament/statement.py", line 1008, in analyze_statement
  File "/usr/local/lib/python3.11/site-packages/parliament-1.6.2-py3.11.egg/parliament/statement.py", line 526, in _check_condition
  File "/usr/local/lib/python3.11/site-packages/jsoncfg/config_classes.py", line 327, in __getattr__
    raise JSONConfigNodeTypeError(
jsoncfg.config_classes.JSONConfigNodeTypeError: Expected a ConfigJSONObject but found ConfigJSONArray. You are trying to get an item from an array as if it was an object. item=value [line=53;col=41]
```

This error is caused by the policy using a `"Bool"` condition with an array `["true"]` instead of the value directly (`"true"`).

The policy is nonetheless valid and comes from <https://github.com/terraform-aws-modules/terraform-aws-iam/blob/aa7ddba39b658088788652b1a0c3221ccf73cf13/modules/iam-group-with-policies/policies.tf>, which was in version 5.11.0 of `terraform-aws-modules/iam` (described on <https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest> as "Terraform module which creates IAM resources on AWS") :

```terraform
    condition {
      test     = "Bool"
      variable = "aws:MultiFactorAuthPresent"
      values   = ["true"]
    }
```

(Note that this Terraform file uses `["true"]` instead of `true`.)

Could you please add support for such policies?

System information:
- Using Parliament from git `master` ([commit `57f45649f512df3302d4185ecf1ec25226006336`](https://github.com/duo-labs/parliament/commit/57f45649f512df3302d4185ecf1ec25226006336), version 1.6.2)
- Using Docker container `docker.io/library/python:3.11` (based on Debian, with Python 3.11) to reproduce the issue, using these commands:
  ```sh
  git clone https://github.com/duo-labs/parliament
  cd parliament/
  pip install -r requirements.txt
  python3 setup.py install
  parliament --auth-details-file iam_get-account-authorization-details.json
  ```

**Comment by rwlodarczyk-xealth** [comment]
Still reproducible on 1.6.4. Here is a minimal repro and what I believe is the root cause, in case it helps.

### Minimal repro

The trigger is a `Bool` condition whose value is a **JSON array** rather than a bare string. Both forms below are valid IAM — the IAM policy grammar allows a condition value to be either a string or an array of strings — but only the scalar form survives:

```python
from parliament import analyze_policy_string

BASE = """{{"Version":"2012-10-17","Statement":[{{
  "Effect":"Allow",
  "Action":"sts:AssumeRole",
  "Resource":"arn:aws:iam::123456789012:role/Example",
  "Condition":{{"Bool":{{"aws:MultiFactorAuthPresent":{}}}}}
}}]}}"""

for value in ('"true"', '["true"]'):
    try:
        result = analyze_policy_string(BASE.format(value))
        print(f"{value:10} -> OK, {len(result.findings)} findings")
    except Exception as exc:
        print(f"{value:10} -> {type(exc).__name__}: {exc}")
```

```
"true"     -> OK, 0 findings
["true"]   -> JSONConfigNodeTypeError: Expected a ConfigJSONObject but found ConfigJSONArray. You are trying to get an item from an array as if it was an object. item=value [line=1;col=184]
```

### Root cause

`Statement._check_condition` in `parliament/statement.py`. The `Bool` pre-check reads the condition value directly:

```python
if operator_type_requirement == "Bool":
    # Get the value that is being compared against
    for c in condition_block:
        value = str(c[1].value).lower()   # <-- raises when c[1] is a JSON array
```

When the value is an array, `c[1]` is a `ConfigJSONArray`, and `jsoncfg` interprets the `.value` attribute access as an object key lookup on an array — hence `item=value` in the message.

The loop immediately below it, in the same function, already handles both shapes correctly:

```python
for block in condition_block:
    key = block[0]
    values = []
    for v in make_list(block[1]):
        values.append(v.value)
```

So the fix is to make the `Bool` pre-check use the same `make_list()` indirection. `make_list` is already imported in this module.

### Proposed fix

```diff
         if operator_type_requirement == "Bool":
             # Get the value that is being compared against
             for c in condition_block:
-                value = str(c[1].value).lower()
-                if value != "true" and value != "false":
-                    self.add_finding(
-                        "MISMATCHED_TYPE_OPERATION_TO_NULL", location=condition_block
-                    )
-                    return False
+                for v in make_list(c[1]):
+                    value = str(v.value).lower()
+                    if value != "true" and value != "false":
+                        self.add_finding(
+                            "MISMATCHED_TYPE_OPERATION_TO_NULL",
+                            location=condition_block,
+                        )
+                        return False
```

This keeps the existing behaviour for the scalar form and for genuinely bad values (a non-boolean still yields `MISMATCHED_TYPE_OPERATION_TO_NULL` and returns `False`), while accepting the array form that IAM permits. With the patch applied, the repro above reports `OK, 0 findings` for both inputs.

For what it is worth, line 526 appears to be the only place in `statement.py` that reaches into a condition value without going through `make_list()`, so this looks like an isolated one-line oversight rather than a pattern repeated elsewhere.

### Note for anyone hitting this downstream

Because the exception propagates out of `analyze_policy_string`, a caller that wraps it in `try/except` will silently skip the entire policy rather than analyzing it — so this can quietly reduce coverage rather than showing up as a loud failure. Until a release includes a fix, normalizing single-element condition value arrays to the scalar form before calling `analyze_policy_string` avoids it, and is semantically equivalent in IAM.
